--  create DB test
-- create table users (name text, age smallint, birthday date); 

-- insert into users (name, age, birthday) values ('Oybek', 49, '1974-06-01');
-- insert into users (name, age, birthday) values ('Behruz', 20, '2003-07-07');
-- insert into users (name, age, birthday) values ('Sally', 10, '2020-05-05');
-- insert into users (name, age, birthday) values ('John', 15, '2012-01-02');

-- drop table users;

-- add new column
-- alter table users add score smallint;

--update column
-- update users set score = 50 where name = 'Oybek';
-- update users set score = 100 where name = 'Behruz';
-- update users set score = 65 where name = 'Sally' AND name = 'John'; --ERROR
-- update users set score = 45 where name = 'Sally' OR name = 'John';

-- select * from users where name like 'O%';
-- select * from users where name like 'A%';

-- select * from users where name like '%y';  -- Sally

-- select * from users order by score desc;  -- like sort by score
-- select * from users order by score asc;

--FUNCTIONS in SQL
-- select avg(score) from users;  -- 56,6
-- select sum(age) from users;  -- 192
-- select count(name) from users;  --6

-- select * from users;

-- serial - next value generated by the sequence as the default value for the column
-- create table login (
-- 	ID serial NOT NULL PRIMARY KEY,
-- 	secret VARCHAR (100) NOT NULL,
-- 	name text UNIQUE NOT NULL
-- );

-- insert into login (secret,name) values ('abc', 'Andrei');
-- insert into login (secret,name) values ('123', 'Sally');
-- insert into login (secret,name) values ('456', 'John');
-- insert into login (secret,name) values ('qaz', 'Oybek');

-- select * from login;

-- Joining Tables
-- select * from users JOIN login ON users.name = login.name;

-- Delete from table
-- delete from users where name='Sally';

select * from users;

--Drop table
-- drop table login;
drop table users;
